---
- name: Provision Ubuntu VM for comfort over ssh
  hosts: default
  vars:
    fd_deb_file: fd-musl_8.0.0_amd64.deb
    fd_deb_url: "https://github.com/sharkdp/fd/releases/download/v8.0.0/{{ fd_deb_file }}"
  tasks:
    - name: Install packages from apt
      apt: 
        pkg: 
        - git 
        - vim
        - tmux
        - cowsay
        - ripgrep
        update_cache: true
        state: present
      become: true
    - name: Install fd debian package
      apt:
        deb: "{{ fd_deb_url }}"
      become: true
    - name: Download fzf
      git:
        repo: https://github.com/junegunn/fzf
        depth: 1
        dest: ~/.fzf
    - name: Install fzf 
      command: ~/.fzf/install --all
    - name: Clone .dotpliki repositorium
      git:
        repo: https://github.com/psacawa/.dotpliki
        dest: "~/.dotpliki"
        bare: true
    - name: Install z
      git: 
        repo: https://github.com/rupa/z
        dest: ~/.local/share/z

    - name: Install Vundle
      git: 
        repo: https://github.com/VundleVim/Vundle.vim.git 
        dest: ~/.vim/bundle/Vundle.vim

    - name: Checkout .dotpliki repositorium
      shell: git --git-dir=$HOME/.dotpliki --work-tree=$HOME checkout -f
      register: dotpliki_checkout_result
